-- CREATE DATABASE "golang-grpc-zmq-sse-be-1";
-- DROP DATABASE "golang-grpc-zmq-sse-be-1";

-- CREATE TABLE dump (
--     id SERIAL PRIMARY KEY,
--     -- identifier TEXT NOT NULL,
--     -- name TEXT NOT NULL,
--     message TEXT NOT NULL,
--     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--     -- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );

SELECT * FROM dump;
-- DROP TABLE dump;